### ISSUE TITLE
[Suggestions & Bugs] Armor Potion Effects

### ISSUE THREAD

**Issue by Viatos** [Shinoow/AbyssalCraft#183] opened 2016-12-26 06:03 UTC
Some potion effects are applied as 12-second buffs; some seem to be applied as tick-long buffs that continually refresh. Suggest standardizing these.

Ethaxium Strength and Regeneration apply, expire, and then reapply instead of remaining constant. Aside from being somewhat frustrating in actual play, it gets visually annoying if you have mods that track your active effects.

The Visage of the Depths overlay, aside from being generally pretty intense for active use, sometimes glitches out and renders most of the world - particularly the Nether - invisible except from the periphery of the effect. Config option to disable would be awesome. Also maybe to set the opacity. I like the idea but it's just too overbearing to wear around.

**Comment by Shinoow** [comment] 2016-12-29 23:00
Night Vision won't be applied as tick-long, since having it being applied for a duration less than 10 seconds results in the screen constantly flashing due to that Potion Effect doing that when there's less than 10 seconds left on the duration.

The effects on the Ethaxium armor are applied randomly for short durations, which leads to that effect (vanilla alone shows the active Potion Effects, so it can be seen there as well). I plan on reworking that armor set, not sure when, though.

I haven't encountered any visuals from it, but the backend code for the overlay hasn't been properly updated for a long time, so that one will likely be fixed with the improvement to that code. I made the inner part of the texture a lot more translucent in 1.9.3.5, but perhaps it needs another round of making it more transparent, or just make a new texture that's easier to see through. I should probably look into adding some finesse to that armor set in general, so that wearing it actually has a purpose, rather than obscuring part of the vision.

**Comment by Ormathonz** [comment] 2017-06-01 22:25
Any way to change the buffs on the Dreadium Samurai set? Constant flashing Strenght, resistance, speed and a super epilepsy inducing night vision really messes everything up. 
The night vision buff is 13 sec, but it keeps refreshing 10(if not more) times per tick causing massive flickering.
Any way to change the code on those things so they dont refresh constantly and breaks brains?

**Comment by Shinoow** [comment] 2017-06-02 07:45
The potion effects are refreshed once every tick, which is pretty normal for things like this. The night vision is set to 13 seconds, which is above the 10 second mark that makes the screen begin to flash until it runs out (effectively not triggering that to happen). 
![2017-06-02_09 41 12](https://cloud.githubusercontent.com/assets/6419600/26715902/ab8575a2-4777-11e7-9128-e03b44c9f31c.png)
The closest I can see to any flashing is that the icons are slightly fading (which they do when they're about to run out, something I could circumvent by setting the buff timer to 40 ticks instead of 20.
What you're describing is something I can't reproduce with AbyssalCraft alone, so if you're seeing this in a modpack, you should report it to the author of said modpack, as this is likely caused by some mod in said modpack.

**Closed** 2019-02-09 22:05 UTC
Labels: suggestion
