### ISSUE TITLE
crash issue when entering portal

### ISSUE THREAD

**Issue by NekoAthena** [Shinoow/AbyssalCraft#324] opened 2018-09-16 22:25 UTC
#### Description:

This error crashes our server when we enter a portal and it begins to load the dimension.

#### Crash report:

(https://pastebin.com/Cu9xA0K6)

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.4.2759
- AbyssalCraft: 1.9.4.12

**Comment by Shinoow** [comment] 2018-09-17 09:31
Duplicate of #322

**Closed by Shinoow** 2018-09-17 09:31 UTC
Labels: duplicate
