### ISSUE TITLE
Abyssalnite Golem spawning too many times

### ISSUE THREAD

**Issue by Daejangnamu** [Shinoow/AbyssalCraft#454] opened 2020-10-30 18:43 UTC
#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge:  1.12.2 - 14.23.5.2854
- AbyssalCraft: 1.12.2-1.10.3

![144](https://user-images.githubusercontent.com/52635462/97744699-0b2d6480-1b2b-11eb-9e27-effd8a6c07f7.png)
![1444](https://user-images.githubusercontent.com/52635462/97744704-0c5e9180-1b2b-11eb-8302-ea72ce036d98.png)

**Comment by Shinoow** [comment] 2020-10-30 22:59
You have some mod installed that's interfering with the mob spawning. I would need a modlist to be able to point out any potential culprit.

**Comment by Shinoow** [comment] 2021-01-03 16:24
Closing this for now.  I can't reproduce nor diagnose the bug with the provided (or lack of) information.

**Closed by Shinoow** 2021-01-03 16:24 UTC
Labels: bug, other mod
