### ISSUE TITLE
[1.10.2-1.9.3.10] Vanilla beacons cause Coralium plague.

### ISSUE THREAD

**Issue by JaSpr** [Shinoow/AbyssalCraft#195] opened 2017-03-10 04:19 UTC
We have repeatedly tested and verified that vanilla beacons cause coralium plague, along with their standard buffs. The only solution anybody on our server has been able to find is to remove the beacon entirely, thus removing the buff as well.

MC: 1.10.2
AC: 1.10.2-1.9.3.10
Forge: 12.18.3.2239
ModPack: All the Mods 1, versions 1.9 - 2.4

**Comment by Shinoow** [comment] 2017-03-10 08:24
I was unable to trigger it, but apparently it shows up (for some reason) before picking the initial buff (after doing so, it's replaced with an upgraded version of the buff).

**Comment by JaSpr** [comment] 2017-03-10 09:24
Players tended to notice it later (not initially upon selecting).  I have been asked about three times over the past month why their bases had coralium plague.  I asked if they placed a beacon recently, they said yes, and i told them it was probably coming from the beacon.  Upon removing the beacons, all cases went away.

**Comment by JaSpr** [comment] 2017-03-10 09:25
Could this have something to do with IngotBlock#isBeaconBase always returning true??

**Comment by Shinoow** [comment] 2017-03-10 10:59
That shouldn't have any effect on it at all (since that makes it possible to use blocks made from ingots of my materials as beacon bases), not to mention I used gold blocks in my test world. Still unable to get the beacon to spread the potion effect, but I can see it in the secondary power section before picking anything from the primary power section.

**Comment by JaSpr** [comment] 2017-03-15 23:29
Here's an example of a beacon emitted Coralium Plague II http://i.imgur.com/Y0leA41.png.

The beacon might need to have the full size base with access to the second tier of effects.

**Comment by Shinoow** [comment] 2017-03-16 13:48
That's exactly what it looks like in my workspace, but I still can't make it emit the potion effect.

**Comment by JaSpr** [comment] 2017-03-16 19:08
ARG

**Comment by Rogonad** [comment] 2017-03-28 02:25
I can confirm this exact problem is happening on my server too, turning off beacons stops the plague

MC: 1.10.2
BloodMagic-1.10.2-2.1.6-75
Forge: 12.18.3.2254

**Comment by Divineaspect** [comment] 2017-03-28 05:21
I think it's a server problem

**Comment by Shinoow** [comment] 2017-03-28 12:49
I'm unable to reproduce this on a dev server, so either it's a mod present in both cases doing something on servers or plugin (provided a server plugin framework is present in both cases) triggering this. Alternatively, if I can get some instructions on how to reproduce this, maybe there's something I can do on my end to circumvent it.

**Comment by Divineaspect** [comment] 2017-03-28 16:52
We don't use plugins, but do have this problem.

**Comment by Rogonad** [comment] 2017-03-28 18:32
It happend instantly after a player went to The End, they died (falling into the void), on respawn at there home everyone on the server within radius of a beacon got the plague. Not sure if that helps but its all info

**Comment by JaSpr** [comment] 2017-04-15 03:43
We do use Sponge on our server... could that have something to do with it?

**Comment by Shinoow** [comment] 2017-04-17 11:37
Since the bug seems to occur without Sponge being present, it shouldn't be a factor.

**Comment by LatentDesire** [comment] 2017-04-17 18:28
Rogonad is it possible that it's a potion ID conflict with Soul Fray from Blood Magic.

**Comment by LemADEC** [comment] 2017-05-06 08:24
Using AbyssalCraft-1.10.2-1.9.4-pre-2.jar, issue is reproduced with:
- lowest tier vanilla beacon (just 9 diamond blocks below)
- never selecting a potion effect in the beacon
- SSP and SMP
- spongeforge-1.10.2-2281-5.2.0-BETA-2300

The issue doesn't appear initially when placing the beacon, something else is needed to trigger it.
On first occurrence, someone went through a portal while the another remained in the area. Breaking the beacon removed the effect.
On second occurrence, the server was restarted.
On third occurrence, I've fueled with a diamond and no effect selected.

When issue is present, the Plague effect will:
- renew every 4 seconds from 11 seconds (7 to 10 displayed),
- applies within 20 blocks radius of the bugged vanilla beacon.
=> this is consistent with Vanilla beacon behavior.

When activating the beacon (selecting Jump effect and adding a diamond), issue is no longer reproduced as the Plague effect properly goes away.

**Comment by JaSpr** [comment] 2017-05-07 03:13
Best bug report I've seen on github @LemADEC

**Comment by Shinoow** [comment] 2017-05-21 14:39
After a bit of digging at various parts of the vanilla code, I believe I've found the source of why the Potion shows up in the Beacon Gui. Vanilla never registers a Potion with the ID 0, which happens to be the ID that's assigned to Coralium Plague when registered (I haven't tested, but the same thing should happen with any other mod adding it's own Potions). The Beacon itself doesn't permit the Potion to be applied, but all of it's logic defaults to 0 when no Potion to emit has been selected. What I suspect happens on Sponge's end would be that their stuff bypasses the vanilla check for the Potions it allows the beacon to apply, therefore allowing the plague to be spread (due to the lack of a "this isn't allowed" check).

**Comment by JonoColwell** [comment] 2017-07-01 07:29
Is there an expected fix for this?

**Comment by Shinoow** [comment] 2017-08-21 15:18
https://github.com/SpongePowered/SpongeCommon/commit/7efe148f02c41ca9a443cc4d45f75c1114e67589

**Closed by Shinoow** 2017-08-21 15:18 UTC
Labels: bug
