### ISSUE TITLE
"Exception ticking world"

### ISSUE THREAD

**Issue by Yowesephth** [Shinoow/AbyssalCraft#157] opened 2016-10-31 06:29 UTC
I can get in my get in my world and play for a bit, but after a while the game freezes momentarily and crashes out. 
http://paste.ee/p/tsAOo

**Comment by Equinox** [comment] 2016-10-31 07:37
Duplicate of https://github.com/Shinoow/AbyssalCraft/issues/155.

**Closed** 2016-10-31 14:14 UTC
