### ISSUE TITLE
crash with altar of inspiration from vampirism placed on abyssalcraft altar

### ISSUE THREAD

**Issue by Hydraheads** [Shinoow/AbyssalCraft#408] opened 2020-01-26 04:57 UTC
#### Description:

Placing an altar of infusion from vampirism on the ritual altar corrupts a chunk and it cannot be fixed with even worldedit. My server is trying hard to fix it but can't find a way.

#### Crash report:

https://pastebin.com/fLbgdwZ8
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.15.jar

#### Latest log file for when the issue was present:

https://pastebin.com/xXSkWxwt

**Comment by Shinoow** [comment] 2020-01-26 10:49
Duplicate of #405 
For now you'll have to revert to a backup (provided you have one, otherwise you could probably get rid of the block through MCEdit).
As with the other case of this, what gave you the idea to replace the Ritual Altar with another block?

**Comment by Hydraheads** [comment] 2020-01-26 16:12
One of the users did not bother reading the wiki I made or ingame guidebook and somehow thought this was how you level up in vampirism. I guess the confusion stems from them being both called "altar", but tbh it makes no sense to me why they would try such a ridiculous thing either. xD

 My hosting service is placing me between a rock and a hard place though. They won't let me download my save to use mcedit on because it is too large, and they aren't helping me change the jvm arguments so I can't really load the save without vampirism either. In other words, I had no option to fix this in the short term other than to tell these fellows to stay out of their base, and edit their playerdata to spawn.

**Closed** 2020-02-02 16:12 UTC
Labels: bug, duplicate
