### ISSUE TITLE
Dreadium Helmet causing constant flickering.

### ISSUE THREAD

**Issue by Desim8r** [Shinoow/AbyssalCraft#212] opened 2017-05-25 01:02 UTC
Playing the Craft of the Titans modpack and the Dreadium Helmet is causing constant flicker particularly around the horizon. I've played other packs with mods that apply permanent night vision without this issue, for example Genetics Reborn in Invasion is rock solid.

I'm finding AbyssalCraft quite enjoyable but this makes the helmet nigh unusuable.

**Comment by Shinoow** [comment] 2017-05-25 11:26
Can you reproduce this with AbyssalCraft alone?

**Comment by gazinga1992** [comment] 2017-06-07 02:28
I also encountered this constant flickering problem with the Dreadium Samurai Helmet on AbyssalCraft-1.11.2-1.9.4-pre-3 on a personal modpack. With just AbyssalCraft, the night vision works correctly. After some testing, it seems like the problem is with the interaction between this mod and the Inventory Pets mod (I used their InventoryPets-1.11.2-1.4.9.5 file for this), which is also in the Craft of the Titans modpack the OP mentioned. Curiously, all other night vision effects (vanilla and modded) work fine, it's just AbyssalCraft that is affected. I don't know if you plan on trying to fix this since this technically isn't a problem with your mod alone, but just thought you'd like to know for future reference.

**Comment by Shinoow** [comment] 2017-06-07 11:24
Since I have the culprit now, might as well take a deeper look on it, and see if there's anything I can do on my end to circumvent whatever they're breaking.

**Comment by Shinoow** [comment] 2017-06-07 12:35
Well, now I know what's triggering it. Apparently Inventory Pets has a tick handler for some special pet abilities, and said tick handler removes the night vision potion effect if the remaining duration is less than 20 seconds and you currently don't have any of the pet that gives it in your hotbar. The icon flickering is due to Inventoy Pets setting the `showParticles` flag to false when applying the Potion Effect (which stops particles from rendering around the player, while also stopping it from showing up in the status effect HUD).

**Comment by Shinoow** [comment] 2017-06-07 21:09
Closing this, since the cause has been found. If you want to keep up with the progress on Inventory Pet's end, https://github.com/capnkirok/Inventory-Pets/issues/186

**Closed by Shinoow** 2017-06-07 21:09 UTC
