### ISSUE TITLE
[1.9] Client crash

### ISSUE THREAD

**Issue by kwpugh** [Shinoow/AbyssalCraft#84] opened 2016-05-01 13:18 UTC
Crash report: http://pastebin.com/raw/1s06hgxP

Forge 1865
Mod: AbyssalCraft-1.9-1.9.1.2.jar

It happens when just walking around, not sure what event is triggering it.

**Comment by Shinoow** [comment] 2016-05-01 13:26
Duplicate of #83, any triggers should be if you were to hit an entity, or any other case clicking the attack button. If you've encountered any other ways to trigger it, please continue the discussion over at the other issue (as it reported there first, and this is the same crash).

**Closed by Shinoow** 2016-05-01 13:26 UTC
