### ISSUE TITLE
random while travelling the world 

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#154] opened 2016-10-31 00:25 UTC
I recently began to get this crash randomly while travelling the world. http://pastebin.com/Fnu46Arb

**Comment by callmebackdraft** [comment] 2016-10-31 09:37
duplicate of #155,

naming your issue better could make it clearer what you are experiencing, and in turn get an answer sooner.

however refer to #155  for more info

**Closed** 2016-10-31 14:14 UTC
