### ISSUE TITLE
Moderately Mysterious Crash.

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#95] opened 2016-05-15 00:42 UTC
http://pastebin.com/HwEUGCds

abyssalcraft{1.9.1.6}

**Comment by Divineaspect** [comment] 2016-05-16 02:22
Once more with feeling.
http://pastebin.com/cJUmQEDd

**Comment by Shinoow** [comment] 2016-05-16 09:42
Hm... no clue what's triggering this, as the only thing it points to is the super call to onUpdate in the Dread Spawn, then to the onUpdate method in EntityMob for the Dreadling (as it doesn't do anything with onUpdate).

**Comment by Divineaspect** [comment] 2016-06-05 20:40
This is a major issue for the viability of a modpack centered on abyssalcraft.

**Comment by Shinoow** [comment] 2016-06-06 19:05
I have no way of reproducing said crash (as I have on clue what's triggering it, you never specified that). If I had a way to produce the crash myself (or a list of actions/conditions that seems to trigger this) I could probably find what's causing it to happen.

**Comment by Divineaspect** [comment] 2016-06-06 19:48
Well, are you willing to use the ATL to download a pack?


Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by Shinoow** [comment] 2016-06-06 20:17
I suppose.

**Comment by Divineaspect** [comment] 2016-06-06 20:36
got irc or discord or anything else you'd prefer to chat through?

I need your mc name to add you to the "tester" list, and after I add you
you'll need to set the server to master, and completely relaunch the ATL
client (so it knows you're you).


Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by Shinoow** [comment] 2016-06-06 21:17
Could go with discord. My mc name is shinoow (no uppercase letters).

**Comment by Divineaspect** [comment] 2016-06-06 21:20
Ok, added you to the ATL end, I must now go run errands alas.

**Comment by Shinoow** [comment] 2016-06-08 10:05
I did a bit of testing with your modpack, and the issue is that a mod (can't remember which) adds a brewable Wither potion (and due to the brewing registry code still being something of a mess in 1.8.9, the potion is merged with the Dread Plague potion). My code doesn't like when a merged potion like that is thrown at a entity denoted immune to the Dread Plague, which then triggers this crash. Can't remember which mod, but one mod present there has a config option for adding the Wither potion effect to a brewable potion (disabling said config option will prevent the crash from occurring).

**Comment by Shinoow** [comment] 2016-06-08 10:47
After some searching, it appears EnderZoo removed the config option that could solve this, so I'm probably gonna have to do something on my end in regards to registering the brewing recipe.

**Comment by Divineaspect** [comment] 2016-06-09 19:57
Regardless of how, that will solve the short term issue.

**Comment by Shinoow** [comment] 2016-06-09 22:38
Yeah, but it's not that big of a deal anyways, since it won't have that much of an impact on the mod.

**Closed** 2016-06-14 20:43 UTC
Labels: bug
