### ISSUE TITLE
[1.12.2] IllegalArgumentException

### ISSUE THREAD

**Issue by SirTwsted** [Shinoow/AbyssalCraft#253] opened 2017-12-10 16:12 UTC
https://pastebin.com/sAGTJ9xu

Minecraft v1.12.2
Forge v14.23.1.2555
AbyssalCraft v1.9.4.2
AbyssalCraft Integration v1.6.2

**Comment by trogarus** [comment] 2017-12-10 18:55
Same as https://github.com/Shinoow/AbyssalCraft/issues/252 and also reported at Chisel https://github.com/Chisel-Team/Chisel/issues/591

**Comment by Shinoow** [comment] 2017-12-10 20:01
Duplicate of #252

**Closed by Shinoow** 2017-12-10 20:01 UTC
Labels: duplicate
