### ISSUE TITLE
[CTD] When looking past page 10 in Neronomicon/Entity

### ISSUE THREAD

**Issue by drakray** [Shinoow/AbyssalCraft#236] opened 2017-09-01 03:38 UTC
https://pastebin.com/1pRAZWQ9

Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.lang.Class.isAssignableFrom(Native Method)
	at com.shinoow.abyssalcraft.common.handlers.InternalNecroDataHandler.lambda$registerInternalPages$0(InternalNecroDataHandler.java:212)

Linux server, Win7 or Mac client

MC 1.11.2
Forge 2454
Abyssalcraft-1.11.2-1.9.4-pre-4

**Comment by Shinoow** [comment] 2017-09-01 10:45
Huh, looks like something managed to sneak past my system for filtering out invalid entity IDs. Can you reproduce it by making a new world, then open a Necronomicon and go to the same page while in survival? If that doesn't trigger it again, try killing a few mobs from some of the installed mods (none from vanilla nor AbyssalCraft, as they shouldn't have any effect on it other than the normal behavior), then open the book again. I can probably add some stricter checks on my end, but this would get me a closer look at what might've caused it.

**Comment by drakray** [comment] 2017-09-01 16:15
New world don't get the crash.
Could it be caused by removed mod? (I removed Headcrumb after having added Abyssalcraft)

**Comment by Shinoow** [comment] 2017-09-01 16:52
Yeah, that explains it. Since the Headcrumbs mobs are no longer registered (as the mod isn't present), trying to use the entity ID fails as nothing is registered to it. I'll have a fix for this in the next release.

**Comment by drakray** [comment] 2017-09-01 19:08
until then is there something I can do to fix this? some nbt value to delete/change maybe?

**Comment by Shinoow** [comment] 2017-09-01 19:53
You should be able to change the Forge Capability data. The capability name is "abyssalcraft:necrodata", and the part you want to remove is any mentions of headcrumbs in "entityTriggers". I think the nbt tag containing the capability data is named something like "ForgeCaps".

**Closed** 2017-10-18 22:30 UTC
Labels: bug
